# -*- coding: utf-8 -*-
"""EV_blast_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxzID178tAAdHMFvYTZrhwJjnu6KkczN
"""

import streamlit as st
import pandas as pd
import joblib

# Load model and encoder
model = joblib.load("ev_blast_prediction_model.pkl")
encoder = joblib.load("label_encoder.pkl")   # rename file properly

st.title("EV Blast Prediction App")

# ===== INPUTS =====

battery_type = st.selectbox(
    "Battery Type",
    encoder["Battery_Type"].classes_
)

poor_cell_design = st.selectbox("Poor Cell Design", [0, 1])
external_abuse = st.selectbox("External Abuse", [0, 1])
poor_battery_design = st.selectbox("Poor Battery Design", [0, 1])
short_circuits = st.selectbox("Short Circuits", [0, 1])

temperature = st.number_input(
    "Temperature",
    min_value=0,
    max_value=100
)

overcharge_overdischarge = st.selectbox(
    "Overcharge / Overdischarge",
    encoder["Overcharge_Overdischarge"].classes_
)

battery_maintenance = st.selectbox(
    "Battery Maintenance",
    encoder["Battery_Maintenance"].classes_
)

# ===== PREDICT BUTTON =====

if st.button("Predict"):

    df = pd.DataFrame({
        "Battery_Type": [battery_type],
        "Poor_Cell_Design": [poor_cell_design],
        "External_Abuse": [external_abuse],
        "Poor_Battery_Design": [poor_battery_design],
        "Short_Circuits": [short_circuits],
        "Temperature": [temperature],
        "Overcharge_Overdischarge": [overcharge_overdischarge],
        "Battery_Maintenance": [battery_maintenance]
    })

    # Apply encoder only to categorical columns
    for col in encoder:
        if col in df.columns:
            df[col] = encoder[col].transform(df[col])

    prediction = model.predict(df)[0]

    # If model returns numbers
    health_map = {0: "Good", 1: "Poor", 2: "Critical"}
    prediction = health_map.get(prediction, prediction)

    if prediction == "Good":
        st.success("Battery Health is Good")
    elif prediction == "Poor":
        st.warning("Battery Health is Poor")
    else:
        st.error("Battery Health is Critical")
