# -*- coding: utf-8 -*-
"""EV_blast_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxzID178tAAdHMFvYTZrhwJjnu6KkczN
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("ev_blast_prediction_model.pkl")
encoder = joblib.load("label_encoder (5).pkl")

st.title("EV_blast_deployment app")


battery_type = st.selectbox("Battery Type", encoder["Battery_Type"].classes_)
poor_cell_design = st.selectbox("Poor Cell Design", [0, 1])
external_abuse = st.selectbox("External Abuse", [0, 1])
poor_battery_design = st.selectbox("Poor Battery Design", [0, 1])
short_circuits = st.selectbox("Short Circuits", [0, 1])
temperature = st.number_input("Temperature", min_value=0, max_value=100)
Overcharge_Overdischarge = st.selectbox("Overcharge_Overdischarge", encoder["Overcharge_Overdischarge"].classes_)
Battery_Maintenance = st.selectbox("Battery_Maintenance", encoder["Battery_Maintenance"].classes_)
Battery_Health = st.selectbox("Battery_Health", encoder["Battery_Health"].classes_)


df = pd.DataFrame({
    "Battery_Type" : [battery_type],
    "Poor_Cell_Design" : [poor_cell_design],
    "External_Abuse" : [external_abuse],
    "Poor_Battery_Design" :	[poor_battery_design],
    "Short_Circuits" : [short_circuits],
    "Temperature" : [temperature],
    "Overcharge_Overdischarge" : [overcharge_overdischarge],
    "Battery_Maintenance" :	[battery_maintenance],
    "Battery_Health" : [battery_health]
})


if st.button("Predict"):

    prediction = model.predict(input_data)[0]

    # Convert numeric output to text (if needed)
    health_map = {0: "Good", 1: "Poor", 2: "Critical"}
    prediction = health_map.get(prediction, prediction)

    if prediction == "Good":
        st.success("Battery Health is Good")
    elif prediction == "Poor":
        st.warning("Battery Health is Poor")
    else:
        st.error("Battery Health is Critical")
