# -*- coding: utf-8 -*-
"""EV_blast_deployment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxzID178tAAdHMFvYTZrhwJjnu6KkczN
"""

import streamlit as st
import pandas as pd
import joblib

model = joblib.load("ev_blast_prediction_model.pkl")
encoder = joblib.load("label_encoder.pkl")

st.title("EV_blast_deployment app")


Battery_Type = st.selectbox("Battery_Type", encoder["Battery_Type"].classes_)
Poor_Cell_Design = st.selectbox("Poor_Cell_Design", encoder["Poor_Cell_Design"].classes_)
External_Abuse = st.selectbox("External_Abuse", encoder["External_Abuse"].classes_)
Poor_Battery_Design = st.number_input("Poor_Battery_Design", 0, 40)
Short_Circuits = st.number_input("Short_Circuits", 0, 40)
Temperature = st.selectbox("Temperature", encoder["Temperature"].classes_)
Overcharge_Overdischarge = st.selectbox("Overcharge_Overdischarge", encoder["Overcharge_Overdischarge"].classes_)
Battery_Maintenance = st.selectbox("Battery_Maintenance", encoder["Battery_Maintenance"].classes_)
Battery_Health = st.selectbox("Battery_Health", encoder["Battery_Health"].classes_)


df = pd.dataFrame({
    "Battery_Type" : [battery_Type],
    "Poor_Cell_Design" : [poor_cell_design],
    "External_Abuse" : [external_abuse],
    "Poor_Battery_Design" :	[poor_battery_design],
    "Short_Circuits" : [short_circuits],
    "Temperature" : [temperature],
    "Overcharge_Overdischarge" : [overcharge_overdischarge],
    "Battery_Maintenance" :	[battery_maintenance],
    "Battery_Health" : [battery_health]
})


if st.button("Predict"):

    prediction = model.predict(input_data)[0]

    # Convert numeric output to text (if needed)
    health_map = {0: "Good", 1: "Poor", 2: "Critical"}
    prediction = health_map.get(prediction, prediction)

    if prediction == "Good":
        st.success("Battery Health is Good")
    elif prediction == "Poor":
        st.warning("Battery Health is Poor")
    else:
        st.error("Battery Health is Critical")
